name: Run tests and linter

on:
  push:
    branches: [main, homework1]
  pull_request:
    branches: [main]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@hv2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: Install requirements
      
        run: |
          cd ml_project
          pip install -e .
      - name: Run tests
        run: |
          cd ml_project
          pytest -v -p no:warnings tests
      - name: Run linter
        run: |
          cd ml_project
          pylint src
