name: Run tests and linter

on:
  push:
    branches: [main, homework1]
  pull_request:
    branches: [main]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -e .
      - name: Run tests
        run: pytest -v -p no:warnings tests
      - name: Run linter
        run: pylint src
