version: 1
formatters:
    simple_formatter:
        class: logging.Formatter
        format: "%(asctime)s %(name)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    file_handler:
        class: logging.FileHandler
        filename: logs/core.log
        level: DEBUG
        formatter: simple_formatter
    stream_handler:
        class: logging.StreamHandler
        stream: ext://sys.stderr
        level: WARNING
        formatter: simple_formatter
loggers:
    build_features:
        level: DEBUG
        handlers: [file_handler]
        propagate: yes
    fit_model:
        level: DEBUG
        handlers: [file_handler]
        propagate: yes
    predict_model:
        level: DEBUG
        handlers: [file_handler]
        propagate: yes
    core:
        level: DEBUG
        handlers: [file_handler]
        propagate: yes
root:
    level: WARNING
    handlers: [stream_handler]
