input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.joblib"
splitting_params:
  test_size: 0.15
  random_state: 1337
features_params:
  categorial_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_column: "target"
model_params:
  model_type: "Random Forest Classifier"
  n_estimators: 500
  criterion: "entropy"
  max_depth: 10
  min_samples_split: 2
  random_state: 1337