version: 1
formatters:
    simple_formatter:
        class: logging.Formatter
        format: "%(asctime)s %(name)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    file_handler:
        class: logging.FileHandler
        filename: report.log
        level: DEBUG
        formatter: simple_formatter
loggers:
    creating_report:
        level: DEBUG
        handlers: [file_handler]
        propagate: no
root:
    level: DEBUG
    handlers: [file_handler]
