input_data_path: "data/raw/heart.csv"
output_model_path: "models/modeal.joblib"
splitting_params:
  test_size: 0.15
  random_state: 1337
features_params:
  categorial_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_column: "target"