name: Run tests and linter

on:
  push:
    branches: [main, homework1]
  pull_request:
    branches: [main]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.6"
        architecture: "x64"
    - name: Install requirements
      working-directory: ./ml_project
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      working-directory: ./ml_project
      run: |
        pytest -v -p no:warnings tests
    - name: Run linter
      working-directory: ./ml_project
      run: |
        pylint src
